### ISSUE TITLE
tested gem install, doesn't work with Vagrant 1.1.5

### ISSUE THREAD

**Issue by becw** [joshmcarthur/vagrant-list#4]
I have the latest Vagrant installed, and I tried to install this with `gem install vagrant-list`. gem silently overwrote my existing vagrant binary, which broke my existing environments.

I'd say this is an issue with gem silently downgrading existing software, but perhaps you might update the readme and to reflect the specific Vagrant versions this plugin is compatible with.

**Comment by joshmcarthur** [comment]
@becw - wow, I'm really sorry about breaking your environment!

I know there's been some changes recently around how vagrant is distributed
and installed, and so it's entirely possible that vagrant-list doesn't load
itself correctly into the vagrant command structure anymore.

I'll give this situation a good test out as soon as I'm home this
afternoon, and see if I can get things fixed up.

Once again, sorry!

On Saturday, April 13, 2013, becw wrote:

> I have the latest Vagrant installed, and I tried to install this with gem
> install vagrant-list. gem silently overwrote my existing vagrant binary,
> which broke my existing environments.
> 
> I'd say this is an issue with gem silently downgrading existing software,
> but perhaps you might update the readme and to reflect the specific Vagrant
> versions this plugin is compatible with.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshmcarthur/vagrant-list/issues/4
> .

## 

Joshua McArthur

Website: joshmcarthur.com http://www.joshmcarthur.com
LinkedIn: http://nz.linkedin.com/in/joshuamcarthur

**Comment by joshmcarthur** [comment]
@becw OK, this took quite a bit longer than I anticipated it would and required almost a complete rebuild, but the gem is now compatible with Vagrant > 1.1.0, so should hopefully not break anyone else's environments.

If you could, I would appreciate it if you could test this and let me know of any problems you run into - I've updated the README with installation instructions, but the version you want is `0.0.6`.

For anyone else reading this who is still running an older version of Vagrant - don't worry - I've kept compatibility with older versions in version `0.0.5`, and also branched the old code for this so that I can continue to issue bugfixes for Vagrant 1.0.0.

**Comment by becw** [comment]
Installing with `vagrant plugin install vagrant-list` works perfectly now with the latest Vagrant. Thank you so much!

This installation method doesn't require adding the `Vagrant.require_plugin "vagrant-list"` line to each VagrantFile, though--the two install methods could be more clearly separated in the readme.

**Comment by joshmcarthur** [comment]
@becw - great! I've just updated the `README` to reflect your feedback, dividing the installation instructions into sections to install using vagrant and install using Rubygems.

**Comment by becw** [comment]
Awesome, you rule!
